name: Fly Deploy
on:
  push:
    branches:
      - deploy
    paths:
      - backend/**
jobs:
  deploy:
    name: Stereos app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions@1.4
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
