name: Fly Deploy
on:
  push:
    branches:
      - deploy
    paths:
      - backend/**
jobs:
  deploy:
    name: Stereos app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd backend
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}