name: Fly Deploy
on:
  push:
    branches:
      - deploy
    paths:
      - backend/**
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Stereos app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PR Review Apps on fly.io
        uses: superfly/fly-pr-review-apps@1.2.0