name: Fly Deploy
on:
  push:
    branches:
      - deploy
    paths:
      - backend/**
jobs:
  deploy:
    defaults:
      run:
        working-directory: backend
    name: Stereos app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}